package lint_test

import (
	"context"
	"flag"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/kmoneil/jr/internal/buildinfo"
	"github.com/kmoneil/jr/internal/cli"

	// Every resource, so the inventory the skill carries is the shipped
	// surface and not only the built-ins.
	_ "github.com/kmoneil/jr/internal/commands"
)

// shippedSkill is where the checked-in copy of the agent skill lives, laid out
// the way a skill loader expects: SKILL.md at the top, references beside it.
//
// It is a committed path rather than .claude/skills/jr, which is where a user
// installs it. `.claude/` is gitignored here, so a skill generated into it
// would be regenerated by every clone and shipped by none.
const shippedSkill = "../../skills/jr"

// updateSkill rewrites the shipped skill instead of comparing against it.
// `make skill` passes it, under the full tag set.
var updateSkill = flag.Bool("update-skill", false,
	"rewrite the shipped agent skill from the binary instead of comparing against it")

// TestTheShippedSkillIsCurrent holds skills/jr to `jr skill`.
//
// The skill is generated for the same reason docs/commands.md is: its command
// inventory comes from the registry, and a hand-maintained second copy is the
// "second place to update" that goes stale on the next command and reads as
// current forever. What is hand-written is the judgment that no declaration can
// carry, and that lives in internal/cli/skillassets where the binary embeds it.
//
// Only the full build is compared. The skill is deliberately profile-aware, so
// a reader build legitimately emits a shorter inventory; asserting that under
// every tag set would mean four checked-in copies of a document whose whole
// point is that you generate the one you need. Under any other tag set this
// asserts the weaker claim that the files exist and carry the hand-written
// half, which is not a skip: `make test` runs untagged, and an assertion that
// skips is an assertion that ran nothing.
func TestTheShippedSkillIsCurrent(t *testing.T) {
	files := skillFiles(t)
	if len(files) < 2 {
		t.Fatalf("the binary emitted %d skill files, which cannot be the whole skill",
			len(files))
	}

	if *updateSkill {
		writeSkill(t, files)
		return
	}
	if buildinfo.Profile() == "full" {
		compareSkill(t, files)
		return
	}
	checkSkillExists(t, files)
}

// skillFiles runs the command for every document the skill carries and returns
// what it wrote, keyed by path relative to the skill directory.
func skillFiles(t *testing.T) map[string]string {
	t.Helper()
	out := map[string]string{"SKILL.md": runSkill(t)}
	for _, ref := range skillReferenceNames(t) {
		out[filepath.Join("references", ref+".md")] = runSkill(t, ref)
	}
	return out
}

// skillReferenceNames asks the binary which references it has, by naming one it
// does not have and reading the candidates back out of the refusal.
//
// Asking rather than listing a constant here is the same rule the skill itself
// follows: a reference added to skillassets is shipped without a second edit,
// and a list in this file could disagree with the binary while both looked
// right.
func skillReferenceNames(t *testing.T) []string {
	t.Helper()
	var out, errOut strings.Builder
	cli.Main(context.Background(), []string{"skill", "\x00not-a-reference"}, cli.Options{
		Stdout: &out,
		Stderr: &errOut,
		Getenv: func(string) string { return "" },
	})
	const marker = "valid values: "
	i := strings.Index(errOut.String(), marker)
	if i < 0 {
		t.Fatalf("the refusal did not list the references it has:\n%s", errOut.String())
	}
	rest := errOut.String()[i+len(marker):]
	rest, _, _ = strings.Cut(rest, "<")
	rest, _, _ = strings.Cut(rest, "\n")

	var names []string
	for n := range strings.SplitSeq(rest, ",") {
		if n = strings.TrimSpace(n); n != "" {
			names = append(names, n)
		}
	}
	if len(names) == 0 {
		t.Fatal("the binary reports no skill references at all")
	}
	return names
}

func runSkill(t *testing.T, args ...string) string {
	t.Helper()
	var out, errOut strings.Builder
	code := cli.Main(context.Background(), append([]string{"skill"}, args...), cli.Options{
		Stdout: &out,
		Stderr: &errOut,
		Getenv: func(string) string { return "" },
	})
	if code != 0 {
		t.Fatalf("jr skill %v exited %v: %s", args, code, errOut.String())
	}
	if out.Len() == 0 {
		t.Fatalf("jr skill %v wrote nothing", args)
	}
	return out.String()
}

func writeSkill(t *testing.T, files map[string]string) {
	t.Helper()
	for name, body := range files {
		full := filepath.Join(shippedSkill, name)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("creating %s: %v", filepath.Dir(full), err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatalf("writing %s: %v", full, err)
		}
	}
	t.Logf("rewrote %s from %d documents", shippedSkill, len(files))
}

func compareSkill(t *testing.T, files map[string]string) {
	t.Helper()
	for name, want := range files {
		got, err := os.ReadFile(filepath.Join(shippedSkill, name))
		if err != nil {
			t.Errorf("reading the shipped skill: %v; run `make skill`", err)
			continue
		}
		if string(got) == want {
			continue
		}
		t.Errorf("%s/%s is stale: %s.\nRun `make skill` to regenerate it.",
			shippedSkill, name, firstSkillDifference(string(got), want))
	}
}

// checkSkillExists is the part of the claim that still holds when the full
// surface is not compiled: the documents are there and carry the hand-written
// half, whatever this build's inventory says.
func checkSkillExists(t *testing.T, files map[string]string) {
	t.Helper()
	for name := range files {
		got, err := os.ReadFile(filepath.Join(shippedSkill, name))
		if err != nil {
			t.Errorf("the shipped skill is missing %s: %v; run `make skill`", name, err)
			continue
		}
		if len(got) == 0 {
			t.Errorf("%s is empty", name)
		}
	}
}

func firstSkillDifference(got, want string) string {
	g, w := strings.Split(got, "\n"), strings.Split(want, "\n")
	for i := range max(len(g), len(w)) {
		gl, wl := "", ""
		if i < len(g) {
			gl = g[i]
		}
		if i < len(w) {
			wl = w[i]
		}
		if gl != wl {
			return "line " + strconv.Itoa(i+1) + "\n  shipped:  " + gl + "\n  binary:   " + wl
		}
	}
	return "the files differ in trailing content"
}
